#!/bin/bash

################################################################################
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
################################################################################

. config/options $1

if [ ! -z "$1" ]; then
  printf "%${BUILD_INDENT}c ${boldred}CLEAN${endcolor}    $1\n" ' '
  export BUILD_INDENT=$((${BUILD_INDENT:-1}+4))

  for i in $BUILD/$1-*; do
    if [ -d $i -a -f "$i/.unpack" ] ; then
      . "$i/.unpack"
      if [ "$STAMP_PKG_NAME" = "$1" ]; then
        printf "%${BUILD_INDENT}c * Removing $i ...\n" ' '
        rm -rf $i
      fi
    else
      rm -rf $i
    fi
  done
  rm -rf $STAMPS/$1
fi
