#!/bin/bash

################################################################################
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
################################################################################

. config/options $1

. packages/virtual/extra/package.mk

for pkg in $PKG_DEPENDS_TARGET ; do
  scripts/pack_extra $pkg
done
